import AgilePlace from './AgilePlace'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	if (globalThis.apiRoot == null) {
		globalThis.apiRoot = new AgilePlace("nacl.leankit.com", "lk@naconsultancy.co.uk", "New1Here9~!", null)
	}
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
